# This file was generated by GoReleaser. DO NOT EDIT.
cask "goguma" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "c02566770fd89524c890cff6b173c1858bd4b0aa588ad9c3d7db688def7062c8"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
    on_arm do
      sha256 "119982ec6d2eb67186c5ae703a853d7e50a7a2eb4804cf334772699c923f99aa"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa1144fefd29699ec4ad943befa434c53a93faf9bda2b2ec0274c5da4e772595"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_linux_amd64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
    on_arm do
      sha256 "403533cc0e8afd203a0dec43208aa9457ff2e927bc99736646fc49e5bdb0d4a2"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_linux_arm64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
  end

  name "goguma"
  desc "Wakes your machine for scheduled jobs, then lets it sleep again"
  homepage "https://github.com/junnam586/goguma"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goguma"

  # No zap stanza required

  caveats <<~EOS
    goguma is installed but not yet running. To set up the background
    services:

      goguma install

    That installs a user-level daemon and a small privileged helper. The
    helper only blocks sleep and schedules wakes; everything else runs
    unprivileged.
  EOS
end
