# This file was generated by GoReleaser. DO NOT EDIT.
cask "goguma" do
  version "0.1.12"

  on_macos do
    on_arm do
      sha256 "e8464d738b19cb86d824ad8641172d1225ace3c5576539262602018591adfa35"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
    on_intel do
      sha256 "2e64d98ecaebaec3e03ced6233361f5a2053726d2be736e61b70de3a9f4062ad"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
  end
  on_linux do
    on_arm do
      sha256 "a7b493e6e0888948007107c45a892571df7e8d10295f2c6ae1c55b73d83dc514"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_linux_arm64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
    on_intel do
      sha256 "6a9787fb20ee9a927e89daf0486d92319e01a6f57e7790a763f62a5d305d7247"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_linux_amd64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
  end

  name "goguma"
  desc "Wakes your machine for scheduled jobs, then lets it sleep again"
  homepage "https://github.com/junnam586/goguma"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goguma"

  # No zap stanza required

  caveats <<~EOS
    goguma is installed but not yet running. To set up the background
    services:

      goguma install

    That installs a user-level daemon and a small privileged helper. The
    helper only blocks sleep and schedules wakes; everything else runs
    unprivileged.
  EOS
end
