# This file was generated by GoReleaser. DO NOT EDIT.
cask "goguma" do
  version "0.1.12"

  on_macos do
    on_arm do
      sha256 "9ce605e26dcbfc3ca6a19ca49641d46f4e09aa763d6ae5857cea83cf677949e2"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
    on_intel do
      sha256 "c7208a033f911cf3277b6f8d83240e4f65c33e0aae5226b9de3eca636ce24790"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
  end
  on_linux do
    on_arm do
      sha256 "08e88afe8f326ac20c902ad93d88fe59621380b21a3d817ce328f8357a3a7ce2"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_linux_arm64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
    on_intel do
      sha256 "f78d3f8c6cc7ed4ad27c8a56a7f62c319cc23855a2329a7d9bf3fd74296dff14"
      url "https://github.com/junnam586/goguma/releases/download/v#{version}/goguma_#{version}_linux_amd64.tar.gz",
        verified: "github.com/junnam586/goguma"
    end
  end

  name "goguma"
  desc "Wakes your machine for scheduled jobs, then lets it sleep again"
  homepage "https://github.com/junnam586/goguma"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goguma"

  # No zap stanza required

  caveats <<~EOS
    goguma is installed but not yet running. To set up the background
    services:

      goguma install

    That installs a user-level daemon and a small privileged helper. The
    helper only blocks sleep and schedules wakes; everything else runs
    unprivileged.
  EOS
end
